name: $(MajorVersion).$(MinorVersion)$(rev:.r)
pool:
  name: Default
resources:
  containers:
  - container: client_packages
    image: ehz/game/client/packages:latest

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.03.0-ce
    releaseType: stable

- task: Docker@2
  displayName: Login to Personal ACR
  inputs:
    command: login
    containerRegistry: eventHorizonGamesConnection

- task: Docker@2
  displayName: Build Image - Packages EventHorizon.Blazor.BabylonJS
  inputs: 
    command: build
    containerRegistry: eventHorizonGamesConnection
    buildContext: $(Build.SourcesDirectory)
    repository: ehz/game/client/packages
    arguments: --build-arg Version=$(Build.BuildNumber) --target dotnet-nuget-push
    tags: |
      latest

- task: Docker@2
  displayName: Push Image (azure) - Packages EventHorizon.Blazor.BabylonJS
  inputs: 
    command: push
    containerRegistry: eventHorizonGamesConnection
    repository: ehz/game/client/packages
    tags: |
      latest

- script: docker run --rm --name push-packages $ACR_NAME.azurecr.io/ehz/game/client/packages:latest --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
  env:
    ACR_NAME: $(ACR_NAME)
    NUGET_API_KEY: $(NUGET_API_KEY)

- task: Docker@2
  displayName: Build Image (docker-hub) - Base EventHorizon.Blazor.BabylonJS 
  inputs: 
    command: build
    containerRegistry: docker-hub
    buildContext: $(Build.SourcesDirectory)
    repository: canhorn/ehz-platform-server-client
    arguments: --build-arg Version=$(Build.BuildNumber)
    tags: |
      latest
      $(Build.BuildNumber)

- task: Docker@2
  displayName: Push Image (docker-hub) - Base EventHorizon.Blazor.BabylonJS 
  inputs: 
    command: push
    containerRegistry: docker-hub
    buildContext: $(Build.SourcesDirectory)
    repository: canhorn/ehz-platform-server-client
    tags: |
      latest
      $(Build.BuildNumber)

- task: Docker@2
  displayName: Build Image (docker-hub) - EventHorizon.Game.Editor 
  inputs: 
    command: build
    containerRegistry: docker-hub
    buildContext: $(Build.SourcesDirectory)
    repository: canhorn/ehz-platform-server-editor
    Dockerfile: $(Build.SourcesDirectory)/EventHorizon.Game.Editor/Dockerfile
    arguments: --build-arg Version=$(Build.BuildNumber)
    tags: |
      latest
      $(Build.BuildNumber)

- task: Docker@2
  displayName: Push Image (docker-hub) - EventHorizon.Game.Editor 
  inputs: 
    command: push
    containerRegistry: docker-hub
    buildContext: $(Build.SourcesDirectory)
    repository: canhorn/ehz-platform-server-editor
    Dockerfile: $(Build.SourcesDirectory)/EventHorizon.Game.Editor/Dockerfile
    tags: |
      latest
      $(Build.BuildNumber)
