name: $(MajorVersion).$(MinorVersion)$(rev:.r)
pool:
  name: Default

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.03.0-ce
    releaseType: stable

- task: Docker@2
  displayName: Build Image - Base EventHorizon.Blazor.BabylonJS 
  inputs: 
    command: build
    containerRegistry: eventHorizonGamesConnection
    buildContext: $(Build.SourcesDirectory)
    repository: ehz/game/client
    arguments: --build-arg Version=$(Build.BuildNumber)
    tags: |
      latest

- task: Docker@2
  displayName: Build Image - Packages EventHorizon.Blazor.BabylonJS
  inputs: 
    command: build
    containerRegistry: eventHorizonGamesConnection
    buildContext: $(Build.SourcesDirectory)
    repository: ehz/game/client/packages
    arguments: --build-arg Version=$(Build.BuildNumber)
    tags: |
      latest