version: "3"
services:
    edge:
        image: selenium/standalone-edge:4.1.1
        container_name: edge
        ports:
            - "4445:4444"
            - 7901:7900

    chrome:
        image: selenium/standalone-chrome:4.1.1
        container_name: chrome
        ports:
            - "4446:4444"
            - 7900:7900

    firefox:
        image: selenium/standalone-firefox:4.1.1
        container_name: firefox
        ports:
            - "4447:4444"
            - 7902:7900
